language: node_js

services:
  - docker

node_js:
  - 11
  - 10

branches:
  only:
    - master

install:
  - travis_retry npm install

script:
  - npm run test:coverage

after_success:
  - npm run codecov

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run build
        - npm run semantic-release
